

LIB_TEST_DIRS = \
  110_testfig \
  210_testplot \
  310_testshade \
  410_testiso \
  450_testplot2D \
  510_boag \
  520_boap \
  610_miguec
   
include ${STOLFIHOME}/programs/c/GENERIC-ROOT-DIR.make
