# Tests of libmroc
# Last edited on 2021-07-07 17:16:46 by jstolfi

LIB_TEST_DIRS := ${wildcard [0-9][0-9][0-9][0-9]_*}
  
LIB_TEST_DIRS_LATER :=

IGNOREDIRS :=
   
include ${STOLFIHOME}/programs/c/GENERIC-ROOT-DIR.make
 
