#Last edited on 2024-06-22 20:44:52 by stolfi

SUBDIRS :=  \
  test_calib_opt \
  test_calib_guess \
  test_calib \
  test_povray_camera \
  test_camera_plot

IGNOREDIRS :=

include ${STOLFIHOME}/programs/c/GENERIC-ROOT-DIR.make
