# Last edited on 2015-10-06 21:25:18 by stolfilocal

PROG := test_bvtable
 
TEST_LIB := libjs.a

TEST_LIB_DIR := ../..

JS_LIBS :=

include ${STOLFIHOME}/programs/c/GENERIC-LIB-TEST.make
 
.PHONY:: do-test

all: do-test

do-test: ${PROG}
	${PROG}

