# Last edited on 2023-02-15 12:23:55 by stolfi

PROG := test_codetree_huff

TEST_LIB := libjs.a
TEST_LIB_DIR := ../..

JS_LIBS = \
  libjs.a
  
include ${STOLFIHOME}/programs/c/GENERIC-LIB-TEST.make

all: check

check:  
	./${PROG}

clean::
