# Last edited on 2024-11-08 11:40:40 by stolfi

SHELL := /bin/bash

TEST_LIB := libtosl.a
TEST_LIB_DIR := ../..

PROG := test_tosl_build_lists

JS_LIBS :=

all: ${PROG}
	${PROG}

include ../../../../GENERIC-LIB-TEST.make
