# Last edited on 2024-10-02 22:14:44 by stolfi

SHELL := /bin/bash

TEST_LIB := libtosl.a
TEST_LIB_DIR := ../..

PROG := tosl_build_lists_test

JS_LIBS :=

all: ${PROG}
	${PROG}

include ../../../../GENERIC-LIB-TEST.make
