# Geometry and linear algebra routines
# Last edited on 2023-10-20 15:50:33 by stolfi

LIBNAME := libalign

IGNORE := \
  hr2_pmap_aff_from_many_pairs.c \
  hr2_pmap_aff_from_many_pairs.h \
  hr2_pmap_aff_from_many_pairs.c \
  hr2_pmap_aff_from_many_pairs.h \
  hr2_pmap_from_many_pairs.c \
  hr2_pmap_from_many_pairs.h

include ${STOLFIHOME}/programs/c/GENERIC-LIB.make
