# Geometry and linear algebra routines
# Last edited on 2022-02-27 23:42:25 by stolfi

LIBNAME := libalign

IGNORE := \
  r2_align_multiscale.c \
  r2_align_multiscale.h \

include ${STOLFIHOME}/programs/c/GENERIC-LIB.make
