# Geometry and linear algebra routines
# Last edited on 2024-09-05 18:51:38 by stolfi

LIBNAME := libalign

IGNORE := \
  hr2_pmap_aff_from_many_pairs.c \
  hr2_pmap_aff_from_many_pairs.h 

include ${STOLFIHOME}/programs/c/GENERIC-LIB.make
