# Last edited on 2009-03-06 20:21:10 by stolfi

PROG := test_enum_orbits
 
TEST_LIB := libjs.a

TEST_LIB_DIR := ../..

JS_LIBS :=

include ${STOLFIHOME}/programs/c/GENERIC-LIB-TEST.make
 
.PHONY:: do-test

all: do-test

do-test: ${PROG}
	${PROG}
