# Last edited on 2008-01-15 00:05:06 by stolfi

LIBNAME := libcpk

NOT_HFILES :=
    
NOT_CFILES = \
  next.c

IGNORE := \
  ${NOT_HFILES} \
  ${NOT_CFILES} 

include ${STOLFIHOME}/programs/c/GENERIC-LIB.make

