#! /bin/csh -f

set usage = "$0 PROBLEM INTEGRATOR SECONDS"

set prbl = "$1"; shift
set intg = "$1"; shift
set secs = "$1"; shift;

gnuplot <<EOF
set terminal X11
plot "${prbl}-true.plot" with lines, \
  "${prbl}-${intg}-6.plot" with points, \
  "${prbl}-${intg}-3.plot" with points, \
  "${prbl}-${intg}-2.plot" with points, \
  "${prbl}-${intg}-1.plot" with points
pause $secs
quit
EOF

exit 0
