#! /bin/csh -f
# Last edited on 2003-09-01 21:30:34 by stolfi

ls -tr *-euler-eerr.plot \
  | sed -e 's/-euler-eerr.plot//g' \
  > .problems

ls -tr quadr-*-eerr.plot \
  | sed -e 's/^quadr-//g' -e 's/-eerr.plot//g' \
  > .methods

foreach prbl ( `cat .problems` )
  foreach mthd ( `cat .methods` )
    show-error-plot ${prbl} ${mthd} 15
  end
end

