# Last edited on 2015-10-07 15:40:33 by stolfilocal

LIBNAME := libstmesh

USE_GL := YES
USE_X11 := YES

EXTRA_C_FLAGS := -pg
  
IGNORE :=

all: uninstall build-lib install

include ${STOLFIHOME}/programs/c/GENERIC-LIB.make

