# Last edited on 2023-02-21 05:06:38 by stolfi

PROG := ic4a
VERS_TAGS := A
DOC_TAGS := P

AREAS := ADM AUD DOC INF TCO TUT
EPS_TAGS := T  ${addsuffix _mods,${AREAS}} ${addsuffix _area,${AREAS}}

include ../ARCHDRAW-TEST.make
