/* See {btc_bubble_parms_write.h} */
/* Last edited on 2015-05-01 23:24:58 by stolfilocal */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>

#include <bool.h>
#include <jsfile.h>

#include <btc_bubble_t.h>

#include <btc_bubble_parms_write.h>

void btc_bubble_parms_write(char* outPrefix, char* tag, int nd, char* dt[], int nb, btc_bubble_t bp[])
  { 
    char* fName = NULL;
    char *fName = jsprintf("%s%s.parms", outPrefix, tag);
    FILE *wr = open_write(fName, TRUE);
    
    fprintf(wr, "# Last edited on DATE TIME by USER\n");
    fprintf(wr, "# Generated by {%s}\n", __FUNCTION__);
    fprintf(wr, "\n");
    
    int jb;
    for (jb = 0; jb < nb; jb++)
      { 
        btc_bubble_t* bpj = &(bp[jb]);

        int id_fin_up = bpj->id_fin_up;
        int id_ini_dn = id_fin_up + bpj->wd_plat;   
        
        fprintf(wr, "  %12.4f", bpj->coef); 
        fprintf(wr, "  %s", dt[bpj->id_ini_sg]); 
        fprintf(wr, "  %8.5f %s %s %8.5f", bpj->rt_up, dt[id_fin_up], dt[id_ini_dn], bpj->rt_dn); 
        fprintf(wr, "  %s  %-12s  %s", dt[bpj->id_fin_sg], bpj->tag, bpj->color); 
        fprintf(wr, "\n"); 
      }
    
    fclose(wr);
    free(fName);
  
  }

