# Last edited on 2024-10-07 21:25:48 by stolfi

SHELL := /bin/bash

TEST_LIB := libtosl.a
TEST_LIB_DIR := ../..

PROG := tosl_mesh_make_ico_test

JS_LIBS :=

all: ${PROG}
	${PROG}
	mview out/test.obj

include ../../../../GENERIC-LIB-TEST.make
