# Last edited on 2024-11-08 11:38:44 by stolfi

SHELL := /bin/bash

TEST_LIB := libtosl.a
TEST_LIB_DIR := ../..

PROG := test_tosl_mesh_make_ico

JS_LIBS :=

all: ${PROG}
	${PROG}
	mview out/test.obj

include ../../../../GENERIC-LIB-TEST.make
