#! /bin/bash
# Last edited on 2009-02-22 22:06:25 by stolfi

# Plots the curve generated by {test_sve_catenary}

file="$1"; shift;
if [[ -r ${file} ]] ; then
  gnuplot << EOF
  set terminal X11
  plot \
    "${file}" using 2:3 with linespoints
  pause 300
EOF
else
  echo "file ${file} missing" 1>&2
fi
