#! /bin/bash
# Last edited on 2025-02-17 02:15:17 by stolfi

# Plots the curve generated by {test_sve_catenary}

file="$1"; shift;

tmp=/tmp/$$

if [[ -r ${file} ]] ; then
  fni_plot.sh < ${file} > ${tmp}.png
  display ${tmp}.png
  rm -f ${tmp}.png
else
  echo "file ${file} missing" 1>&2
fi
