# Geometry and linear algebra routines
# Last edited on 2024-09-19 13:00:10 by stolfi

LIBNAME := libmultifok

IGNORE := \
  multifok_image_stack.h \
  multifok_image_stack.c

include ${STOLFIHOME}/programs/c/GENERIC-LIB.make
