# Last edited on 2017-10-25 18:06:36 by stolfilocal

ALL_TESTS := \
  test1

SUBDIRS := ${ALL_TESTS}  
  
include ${STOLFIHOME}/programs/c/GENERIC-ROOT-DIR.make

all: check

check:  build-tests check
