# Last edited on 2024-12-24 18:38:18 by stolfi

LIBNAME := libpst

IGNORE := \
  pst_adjust_weights.c \
  pst_img_graph.c \
  pst_img_graph_from_maps.c \

include ${STOLFIHOME}/programs/c/GENERIC-LIB.make
