# Last edited on 2024-10-04 14:35:03 by stolfi

SHELL := /bin/bash

TEST_LIB := libtosl.a
TEST_LIB_DIR := ../..

PROG := tosl_mesh_test

JS_LIBS :=

all: ${PROG}
	${PROG}

include ../../../../GENERIC-LIB-TEST.make
