test_sve_img_match.o: test_sve_img_match.c
test_sve_img_match.o: /home/jstolfi/include/bool.ho
test_sve_img_match.o: /home/jstolfi/include/sign.ho
test_sve_img_match.o: /home/jstolfi/include/float_image.ho
test_sve_img_match.o: /home/jstolfi/include/float_image_mask.ho
test_sve_img_match.o: /home/jstolfi/include/float_image_transform.ho
test_sve_img_match.o: /home/jstolfi/include/argparser.ho
test_sve_img_match.o: /home/jstolfi/include/r3x3.ho
test_sve_img_match.o: /home/jstolfi/include/r3.ho
test_sve_img_match.o: /home/jstolfi/include/r2_extra.ho
test_sve_img_match.o: /home/jstolfi/include/rn.ho
test_sve_img_match.o: /home/jstolfi/include/affirm.ho
test_sve_img_match.o: /home/jstolfi/include/indexing.ho
test_sve_img_match.o: /home/jstolfi/include/wt_table.ho
test_sve_img_match.o: /home/jstolfi/include/jsfile.ho
test_sve_img_match.o: /home/jstolfi/include/js.ho
test_sve_img_match.o: /home/jstolfi/include/vec.ho
test_sve_img_match.o: /home/jstolfi/include/minn_plot.ho
test_sve_img_match.o: ../../sve_minn.ho

