# Last edited on 2025-04-27 02:45:09 by stolfi

LIBNAME := libpstzin2

IGNORE := \
  psgr_integrate_recursive.h \
  psgr_integrate_recursive.c \
  psgr_integrate_iterative.h \
  psgr_integrate_iterative.c \
  psgr_integrate.h \
  psgr_integrate.c

include ${STOLFIHOME}/programs/c/GENERIC-LIB.make
