# Last edited on 2025-03-14 16:21:57 by stolfi

LIBNAME := libpstzin2

IGNORE := \
  pst_gr_shrink.h \
  pst_gr_shrink.c \
  pst_gr_integrate_recursive.h \
  pst_gr_integrate_recursive.c \
  pst_gr_integrate_iterative.h \
  pst_gr_integrate_iterative.c \
  pst_gr_integrate.h \
  pst_gr_integrate.c \
  pst_gr_copy.h \
  pst_gr_copy.c \

include ${STOLFIHOME}/programs/c/GENERIC-LIB.make
