# Last edited on 2023-02-05 18:05:51 by stolfi

PROG := test_codetree

TEST_LIB := libjs.a
TEST_LIB_DIR := ../..

JS_LIBS = \
  libjs.a
  
include ${STOLFIHOME}/programs/c/GENERIC-LIB-TEST.make

all: check

check:  
	./${PROG}

clean::
