# Last edited on 2021-12-16 20:00:24 by stolfi
# Makefile for libimg - an old set of image hacks

LIBNAME := libimg

IGNORE := \
  float_image_geostereo_multiscale.c \
  float_image_align_enum.h \
  float_image_align_enum.c \
  float_image_align_quadopt.h \
  float_image_align_quadopt.c \
  float_image_align_multiscale.h \
  float_image_align_multiscale.c \
  uint16_image_read_gen.c \
  uint16_image_write_gen.c \
  uint16_image_scale.h \
  uint16_image_scale.c \
  jsdithers.c

include ${STOLFIHOME}/programs/c/GENERIC-LIB.make
