# Last edited on 2017-09-14 16:34:55 by jstolfi
# Makefile for libimg - an old set of image hacks

LIBNAME := libimg

IGNORE := \
  float_image_geostereo_multiscale.c \
  uint16_image_read_gen.c \
  uint16_image_write_gen.c \
  uint16_image_scale.h \
  uint16_image_scale.c \
  float_image_align.c \
  jsdithers.c

include ${STOLFIHOME}/programs/c/GENERIC-LIB.make
