# Last edited on 2024-12-18 23:33:35 by stolfi
# Makefile for libimg - an old set of image hacks

LIBNAME := libimg

OTHER_C_FLAGS := -pg

IGNORE := \
  float_image_geostereo_multiscale.c \
  uint16_image_scale.h \
  uint16_image_scale.c \
  
#   uint16_image_read_gen.c \
#   uint16_image_write_gen.c \
#   jsdithers.c \

include ${STOLFIHOME}/programs/c/GENERIC-LIB.make
