.\" (****************************************************************************)
.\" (* (C) Copyright 1992 Universidade Estadual de Campinas (UNICAMP)           *)
.\" (*                    Campinas, SP, Brazil                                  *)
.\" (*                                                                          *)
.\" (* Authors:                                                                 *)
.\" (*                                                                          *)
.\" (*   Tomasz Kowaltowski  - CS Dept, UNICAMP <tomasz@dcc.unicamp.br>         *)
.\" (*   Claudio L. Lucchesi - CS Dept, UNICAMP <lucchesi@dcc.unicamp.br>       *)
.\" (*   Jorge Stolfi        - CS Dept, UNICAMP <stolfi@dcc.unicamp.br>         *)
.\" (*                                                                          *)
.\" (* This file can be freely distributed, modified, and used for any          *)
.\" (*   non-commercial purpose, provided that this copyright and authorship    *)
.\" (*   notice be included in any copy or derived version of this file.        *)
.\" (*                                                                          *)
.\" (* DISCLAIMER: This software is offered ``as is'', without any guarantee    *)
.\" (*   as to fitness for any particular purpose.  Neither the copyright       *)
.\" (*   holder nor the authors or their employers can be held responsible for  *)
.\" (*   any damages that may result from its use.                              *)
.\" (****************************************************************************)
.\"
.nh
.TH MainAutomaton 1
.SH Name
AutoAnalysis \- analysis of automata for finite word lists
.SH Synopsis
\fBAutoAnalysis\fR [ \fIoptions\fR ] [ \fB<\fR \fIstatefile\fR ]
.SH Description
\fBAutoAnalysis\fR analyzes an automaton that recognizes a finite language.
.PP
\fBAutoAnalysis\fR applies certain heuristics
(described in \fIJBCS\fR \fB1\fR(3), 36\-42)
to identify lexical categories, and to
and uncover possible errors and omissions
in the wordlist.
.PP
See the source for more details.
.SH Bugs
Likely.
.SH Author
C. L. Lucchesi, T. Kowaltowski, J. Stolfi (Institute of Computing, UNICAMP)

