.\" (****************************************************************************)
.\" (* (C) Copyright 1992 Universidade Estadual de Campinas (UNICAMP)           *)
.\" (*                    Campinas, SP, Brazil                                  *)
.\" (*                                                                          *)
.\" (* Authors:                                                                 *)
.\" (*                                                                          *)
.\" (*   Tomasz Kowaltowski  - CS Dept, UNICAMP <tomasz@dcc.unicamp.br>         *)
.\" (*   Claudio L. Lucchesi - CS Dept, UNICAMP <lucchesi@dcc.unicamp.br>       *)
.\" (*   Jorge Stolfi        - CS Dept, UNICAMP <stolfi@dcc.unicamp.br>         *)
.\" (*                                                                          *)
.\" (* This file can be freely distributed, modified, and used for any          *)
.\" (*   non-commercial purpose, provided that this copyright and authorship    *)
.\" (*   notice be included in any copy or derived version of this file.        *)
.\" (*                                                                          *)
.\" (* DISCLAIMER: This software is offered ``as is'', without any guarantee    *)
.\" (*   as to fitness for any particular purpose.  Neither the copyright       *)
.\" (*   holder nor the authors or their employers can be held responsible for  *)
.\" (*   any damages that may result from its use.                              *)
.\" (****************************************************************************)
.\"
.\" Last modified on 94-12-03 15:50
.nh
.TH MainAutomaton 1
.SH Name
Example \- Example of a Modula-3 program using the libm3reduced library
.SH Synopsis
\fBExample\fR \fB-help\fR
.PP
\fBExample\fR \fB-load\fR \fIdmpfile\fR [ \fB-log\fR \fIlogfile\fR ] 
\fB>\fR \fIoutputfile\fR
.SH Description
\fBExample\fR prints to standard output all the words accepted of the automaton
\fIdmpfile\fR.
Any error messages are printed to the specified
\fIlogfile\fR,
or to the standard error output if the 
\fB-log\fR argument is not given.
.PP
See the source for more details.
.SH Bugs
Likely.
.SH Author
C. L. Lucchesi, T. Kowaltowski, J. Stolfi (Institute of Computing, UNICAMP)

