.\" (****************************************************************************)
.\" (* (C) Copyright 1992 Universidade Estadual de Campinas (UNICAMP)           *)
.\" (*                    Campinas, SP, Brazil                                  *)
.\" (*                                                                          *)
.\" (* Authors:                                                                 *)
.\" (*                                                                          *)
.\" (*   Tomasz Kowaltowski  - CS Dept, UNICAMP <tomasz@dcc.unicamp.br>         *)
.\" (*   Claudio L. Lucchesi - CS Dept, UNICAMP <lucchesi@dcc.unicamp.br>       *)
.\" (*   Jorge Stolfi        - CS Dept, UNICAMP <stolfi@dcc.unicamp.br>         *)
.\" (*                                                                          *)
.\" (* This file can be freely distributed, modified, and used for any          *)
.\" (*   non-commercial purpose, provided that this copyright and authorship    *)
.\" (*   notice be included in any copy or derived version of this file.        *)
.\" (*                                                                          *)
.\" (* DISCLAIMER: This software is offered ``as is'', without any guarantee    *)
.\" (*   as to fitness for any particular purpose.  Neither the copyright       *)
.\" (*   holder nor the authors or their employers can be held responsible for  *)
.\" (*   any damages that may result from its use.                              *)
.\" (****************************************************************************)
.\"
.\" Last modified on 93-08-06 19:30
.nh
.TH  IdealClasses 1
.SH Name
IdealClasses \- determination of ideal classes for an automaton

.SH Syntax
.B IdealClasses [ options ] 

.SH Description
.B IdealClasses
determines ideal classes for given sets of endings and for a given
automaton of words

See the source for more details.
.SH Bugs
Likely.

.SH Author
C. L. Lucchesi, T. Kowaltowski, J. Stolfi (CS Dept. --- UNICAMP)

