.\" (****************************************************************************)
.\" (* (C) Copyright 1992 Universidade Estadual de Campinas (UNICAMP)           *)
.\" (*                    Campinas, SP, Brazil                                  *)
.\" (*                                                                          *)
.\" (* Authors:                                                                 *)
.\" (*                                                                          *)
.\" (*   Tomasz Kowaltowski  - CS Dept, UNICAMP <tomasz@dcc.unicamp.br>         *)
.\" (*   Claudio L. Lucchesi - CS Dept, UNICAMP <lucchesi@dcc.unicamp.br>       *)
.\" (*   Jorge Stolfi        - CS Dept, UNICAMP <stolfi@dcc.unicamp.br>         *)
.\" (*                                                                          *)
.\" (* This file can be freely distributed, modified, and used for any          *)
.\" (*   non-commercial purpose, provided that this copyright and authorship    *)
.\" (*   notice be included in any copy or derived version of this file.        *)
.\" (*                                                                          *)
.\" (* DISCLAIMER: This software is offered ``as is'', without any guarantee    *)
.\" (*   as to fitness for any particular purpose.  Neither the copyright       *)
.\" (*   holder nor the authors or their employers can be held responsible for  *)
.\" (*   any damages that may result from its use.                              *)
.\" (****************************************************************************)
.\"
.nh
.TH TestReducedPair 1
.SH Name
TestReducedPair \- tests the ReducedPair interface
.SH Synopsis
\fBTestReducedPair\fR [ \fIoptions\fR ]
.SH Description
\fBTestReducedPair\fR
is test program for the 
\fBReducedPair\fR
interface of the
\fBlibm3reduced\fR
library.
.PP
See the source code for details.
.SH Bugs
They are its raison d'etre.
.SH Challenges for the bored
Find more exciting tests.
.SH Author
Jorge Stolfi (Institute of Computing, UNICAMP)

