# Last edited on 2016-04-13 11:57:22 by stolfilocal

LIBNAME := libstpoly

USE_GL := NO
USE_X11 := NO

EXTRA_C_FLAGS := -pg
  
IGNORE :=

all: uninstall build-lib install

include ${STOLFIHOME}/programs/c/GENERIC-LIB.make

