# Last edited on 2023-02-06 06:02:46 by stolfi

PROG := test_huff_tree

TEST_LIB := libjs.a
TEST_LIB_DIR := ../..

JS_LIBS = \
  libjs.a
  
include ${STOLFIHOME}/programs/c/GENERIC-LIB-TEST.make

all: check

check:  
	./${PROG}

clean::
