# Geometry and linear algebra routines
# Last edited on 2024-11-28 15:50:47 by stolfi

LIBNAME := libgausol

IGNORE := \
  gausol_residual.h gausol_residual.c

include ${STOLFIHOME}/programs/c/GENERIC-LIB.make
