#! /bin/csh -f
# Last edited on 2006-03-14 11:26:36 by stolfi

# Converts a lisp-like expression to equivalent pseudocode.
# See comments in ${STOLFIHOME}/lib/expr-to-pcode.lsp

if ( $#argv != 1 ) then
  echo "Usage:"
  echo "  $0 <exprname>"
  echo "will read file \"<exprname>.expr\" and write \"<exprname>.pcode\""
  exit 1
endif

set lsplib = "${STOLFIHOME}/lib"

clisp << EOF
(load "${lsplib}/expr-to-pcode.lsp")
(parse "$1")
EOF
