# Tests of libflt 
# Last edited on 2019-04-09 19:08:13 by jstolfi

LIB_TEST_DIRS := \
  test_fget \
  test_hermite3 \
  test_spline_interp \
  test_ulist \
  test_indexing \
  test_enum_orbits \
  test_jsmath \
  test_now \
  test_sleep \
  test_sort \
  test_sort_speed \
  test_tbfind \
  test_jsrandom \
  test_mst \
  test_opf \
  test_pqueue
  
LIB_TEST_DIRS_LATER :=

IGNOREDIRS := \
  220_test_ulist
   
include ${STOLFIHOME}/programs/c/GENERIC-ROOT-DIR.make
 
